Review
thebeastxdxd/my_ps pull request #2
Opened 2020-10-31 17:28 UTC by thebeastxdxd

2020-10-31 18:33 UTC, yoavgur requested changes
Looks really good! I left a lot of comments mainly so you'll have a bunch of work to do. A lot of it is syntactical stuff, but the big things include:
* Macros are cool, use the more often
* Always check what the return values of library calls are and handle them accordingly
* Error handling is super important!!
* Try using fewer mallocs
  * When using mallocs, be SUPER sure you free everything in every situation.
* Makefile are cool!

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    full_path = malloc(strlen(PROC_PATH) + strlen(pid) + strlen(pid_info) + 2);
What is the 2 over there? Either #define it or explain it

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    sprintf(full_path, "%s/%s/%s", PROC_PATH, pid, pid_info);
Why no beginning slash?

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    if (fp == NULL) {
Same comment as line 119 in terms of macro

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    fscanf(fp, "%d %ms %*c %d %d", &info->pid, &info->cmdline, &info->ppid, &info->gid);
Really cool! But how do you know fscanf worked?

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    r_bytes = fread(status_data, 1, MID_BUF_SIZE, fp);
How do you know you read enough?

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    status_data = (char*)malloc(MID_BUF_SIZE);
Why use malloc?

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +        return -1;
If you return here you didn't free `status_data`

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    sscanf(uid_index, "%*s\t%d\t%d\t%*d\t%*d\n", &info->ruid, &info->euid);
Cool! But how do you sscanf worked?

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +int parse_status(char* stat_path, pid_info* info) {
If you really want to be cool, don't return an int as an error code - create your own type to signify am error code

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    char* cmdline_data = NULL;
Good job predefining everything to default values. Ahavti!

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    r_bytes = fread(cmdline_data, 1, MID_BUF_SIZE, fp);
I'm pretty sure there's a max length to be expected in the cmdline but maybe I'm wrong. If there is better use that than an arbitrary size. In fact, if there isn't you should explain why MID_BUF_SIZE is the chosen size

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    r_bytes = fread(cmdline_data, 1, MID_BUF_SIZE, fp);
I would #define the 1 here

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +            cmdline_data[i] = ' ';
Add a comment explaining why you do this

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    if (info->cmdline != NULL) {
I don't understand this block. Why would it not be null? It's a bit hard for me to go over the code properly since I'm on my phone

2020-10-31 18:33 UTC, yoavgur commented on linked_list.c
> +#include <stdio.h>
It's really cool that you decided to implement a linked list! I'm not going over it right now cause I'm dedded from everything else, but in general I think it might be a bit overkill for what the project calls for (which is printing a process list). Try to think of a way not to have to use a linked list in your solution.

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +#define MIN_BUF_SIZE 256
All of these defined are #noice

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +#include <sys/types.h>
Are you using ALL of these includes? If not, delete the unused ones.

2020-10-31 18:33 UTC, yoavgur commented on main.c
> +    stat_path = join_proc_path(pid, STAT);
Regarding all of your function calls, how would you know if it failed? You one of the functions could've failed and you just keep going normally

2020-11-02 15:17 UTC, tomerli97 commented on Makefile
> +run: main.c linked_list.c
Also, read about the .PHONY command in Makefiles.

2020-11-02 16:39 UTC, tomerli97 reviewed
Part1

2020-11-27 12:44 UTC, yoavgur reviewed
Looks much much better! A lot simpler and more coherent. You don't necessarily have to fix all of the comments I made, just go over them. The main thing is to remember to think about all possible paths a function can take and to make it so that allocated / opened resources are always freed / closed. Nice! :)

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    // errno = 0;
The man page probably says that upon error NULL will be returned and errno will be set accordingly. Thus if NULL is returned you can be assured errno will be set and that you aren't looking at an old value

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    printf("%-10s %-10s %-10s %-10s %-10s %-10s\n", "EUID", "PID", "PPID", "GID", "NAME", "CMD");
Nice formatting!

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +            CHECK(parse_pid(&info, proc_ent->d_name) == SUCCESS_STATUS);
You can add a special check for calling functions, instead of always comparing it to SUCCESS_STATUS

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +        pid_info_t info = {0};
It might not be the best to redefine the variable every iteration performance-wise. Good to keep in mind.

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    CHECK(pid != NULL);
Good job with these checks!

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +static error_status_t join_proc_path(char* path, const char* pid, const char* pid_info) {
Good job with the consts!

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    join_proc_path(stat_path, pid, STAT);
Make sure to check the return code

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    CHECK(fclose(fp) == 0);
If `fscanf` fails you don't close `fp`

2020-11-27 12:44 UTC, yoavgur commented on main.c
> +    fp = fopen(stat_path, "r");
As far as I could tell you never close this handle

2020-11-27 17:03 UTC, tomerli97 commented on main.c
> +    join_proc_path(stat_path, pid, STAT);
This can fail so `CHECK` this too

2023-10-07 08:23 UTC, closed without merging